### ISSUE TITLE
"Show completely uncovered files only" hides a file with 0 code coverage

### ISSUE THREAD

**Issue by sylvestre** [marco-c/code-coverage-reports#21]
convert_UTF.c => 0 code coverage

https://codecov.io/gh/mozilla/gecko-dev/src/fb18cb09bdda24570581ebd33e05b3dcc1e4ba9e/toolkit/crashreporter/google-breakpad/src/common/convert_UTF.c

_Show completely uncovered files only_ on
https://marco-c.github.io/code-coverage-reports/#toolkit/crashreporter/google-breakpad/src/common
Will remove it from the list

**Comment by marco-c** [comment]
In the revision of the zero coverage report, some parts of the file were covered: https://codecov.io/gh/mozilla/gecko-dev/src/b36972ff916da03c20b61a67d77b79facb287a44/toolkit/crashreporter/google-breakpad/src/common/convert_UTF.c.

The mismatch might be due to some intermittent test failure which caused some crash (the `ConvertUTF8toUTF16` function is executed by https://dxr.mozilla.org/mozilla-central/source/toolkit/crashreporter/breakpad-client/minidump_file_writer.cc#181).
